'use strict';

module.exports = {
    init : function (editor) {
        atom.workspaceView.command('proton-gist:public', function () {
            create(true);
        });

        atom.workspaceView.command('proton-gist:private', function () {
            create(false);
        });
    }
};

function create(isPublic) {
    var request = new XMLHttpRequest();
    var response = null;
    var url = 'https://api.github.com/gists';
    var editor = atom.workspace.activePaneItem;

    var data = {
        "description": "Generated by proton-gist http://github.com/ankr/proton-gist",
        "public": isPublic,
        "files": {}
    };
    data.files[editor.getTitle()] = {
        "content": editor.buffer.cachedText
    };

    request.onreadystatechange = function() {
        if (request.readyState === 4) {
            if (request.status !== 201) {
                alert('Something went wrong when creating gist - check console!');
                console.log(request);
                return;
            }

            response = JSON.parse(request.responseText);
            editor.moveCursorToBottom();
            editor.insertText('\n' + response.html_url);
            editor.moveCursorToBeginningOfLine();
            editor.cutToEndOfLine();
            editor.deleteLine();
        }
    };

    request.open('POST', url, true);
    request.send(JSON.stringify(data));
};
