'use strict';

module.exports = {
    init : function () {
        atom.workspaceView.command('proton-gist:public', function () {
            create(true);
        });

        atom.workspaceView.command('proton-gist:private', function () {
            create(false);
        });
    }
};

/**
 * Create a gist with the content of the current file
 * Uses title name of current window as the filename in gist.
 *
 * If `protonGist.githubToken` is provided, in the configurations file, the gist
 * will be created on that users account.
 *
 * @param boolean isPublic If TRUE the created gist will be public
 * @return void
 */
function create(isPublic) {
    var request = new XMLHttpRequest();
    var response = null;
    var url = 'https://api.github.com/gists';
    var editor = atom.workspace.activePaneItem;
    var content = editor.getSelectedText() || editor.buffer.cachedText;
    var token = atom.config.get('protonGist.githubToken');

    var data = {
        "description": "Generated by proton-gist http://github.com/ankr/proton-gist",
        "public": isPublic,
        "files": {}
    };
    data.files[editor.getTitle()] = {
        "content": content
    };

    request.onreadystatechange = function() {
        if (request.readyState === 4) {
            if (request.status !== 201) {
                alert('Something went wrong when creating gist - check console (Cmd-alt-i)!');
                console.log(request);
                return;
            }

            response = JSON.parse(request.responseText);

            // Add text to document and cut it out - hack to get it into clipboard
            editor.moveCursorToBottom();
            editor.insertText('\n' + response.html_url);
            editor.moveCursorToBeginningOfLine();
            editor.cutToEndOfLine();
            editor.deleteLine();

            alert('Gist created - url is in your clipboard!');
        }
    };

    request.open('POST', url, true);

    if (token) {
        request.setRequestHeader('Authorization', 'token ' + token);
    }

    request.send(JSON.stringify(data));
};
